### ISSUE TITLE
align utility function prefixes

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.multi.loanbook#132]
We have a variety of `validate_*()`, `abort_*()`, and `stop_if_not_*()` functions here (I take significant responsibility for that, though the misalignment was mostly created when importing the functions from pacta.multi.loanbook.analysis and pacta.multi.loanbook.plot).

Additionally, through my experience building pacta.data.validation, I came to the conclusion of using `assert_*()` and `is_*()` as [prefixes for such functions](https://github.com/RMI-PACTA/pacta.data.validation/issues/74), for the purpose of keeping the prefixes reasonably short while also clearly identifying which functions throw an error versus those that return `TRUE` or `FALSE`.

@jacobvjk @jdhoffa I'd like to decide which style we prefer here and implement that universally in this package.

- related #227
- related #228
- related #229

**Comment by jdhoffa** [comment]
I don't have strong views on this, but since we are getting pretty semantic here, here's a few thoughts: 
* I like `is_*`, it's clear that the result of that will be `TRUE` or `FALSE`
* I like `stop_if_not_*`, it's clear that if NOT, the result of that will stop the execution of the function
* `abort_*`, basically the same as `stop_*`, just pick one I guess. `stop` is probably slightly more idiomatic 
* `assert_*`, is a bit ambiguous. It's not immediately obvious to me what happens if the assertion is not met. I could imagine either a `stop` or a `FALSE` might be reasonable outcomes.
* `validate_*` seems totally ambiguous to me

**Comment by cjyetman** [comment]
`assert` is commonly used in other languages [like Python](https://www.w3schools.com/python/ref_keyword_assert.asp) for this behavior (if `TRUE` do nothing, otherwise error), and e.g. is used in [{checkmate}](https://mllg.github.io/checkmate/articles/checkmate.html#function-overview) (just FYI that's where that comes from)

I think the logic is that `is_*()` evokes a question with an answer, `TRUE` or `FALSE`, whereas `assert_*()` evokes an action, error if not or continue without error.

**Comment by jdhoffa** [comment]
@cjyetman totally understood! It's used a lot in Rust too with the same functionality. 

I was just putting on my incredibly nit-picky hat, and commenting on the fact that based exclusively on the name it's not immediately/ totally unambiguous, but of course with additional context/ experience it is more clear 😊

but anyway, I leave it to you and @jacobvjk  to decide, I'm more than happy with any of the approaches

**Comment by cjyetman** [comment]
@jdhoffa @jacobvjk I believe this is still relevant, but it would be a nice-to-have to ease development and understanding of the code, not a critical task.

**Comment by jdhoffa** [comment]
Seems related to #54

**Comment by cjyetman** [comment]
yes, conceptually related, but targeted at different sets of thing that could be aligned
