### ISSUE TITLE
feat: maybe force `start_year` to be the start year of the scenario(s) used

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.multi.loanbook#220]
Would the analysis even work (methodologically) if a different `start_year` was chosen? If not, we should probably just force that they use the correct one, rather than give an option that could be set incorrectly. 

https://github.com/RMI-PACTA/pacta.multi.loanbook/blob/c0bc24e76f7f7b72d4c3e0bf9458011f0d4f4aa1/example.config.yml#L17-L19

**Comment by jacobvjk** [comment]
I was wondering about that in the past.. I think one issue with this used to be that the emission intensity pathways did not always have the implied start year as the first year in the data set. this seems to have been fixed though, since the scenario data prep has been overhauled. I think ideally the code would

- identify the start year of the scenarios
- validate that, if both TMS and EI scenarios are used, they have the same minimum year
- validate that the abcd have a corresponding year

If all these conditions are met, the start year can be set automatically. If not, the user should probably fix the input data. What do you think? We could also fix the forward looking timeframe at 5, if we want to.

**Comment by jdhoffa** [comment]
Hmm, actually now that we discuss it, I wonder if having data-inferred parameters is a bit brittle (for exactly the case you mention, what if the scenario data is misformatted for some reason). 

I think one middle ground approach could be to:
- Allow the user to set `start_year`
- Validate the parameterized `start_year` against the `min(year)` of each scenario dataset used
- Throw informative warnings in case they are not all aligned

Because it's true, for TMS we very much expect start_year == min(year), but for EI it is not really "required"

**Comment by jdhoffa** [comment]
Given that we cannot assure that the `SDA` and `TMS` scenarios will have identical values of `min(year)`, we have decided that we should _not_ do this, and the user should manually set their `start_year` in the config (as is currently the case).
